steps:
  - uses: actions/checkout@v4
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v4
    with:
      node-version: ${{ matrix.node-version }}
  - uses: shivammathur/setup-php@v2
    with:
      php-version: 7.4
  - run: npm install --legacy-peer-deps
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
