name: 'install php and deps'
description: 'install php and deps'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
    - run: npm install --legacy-peer-deps
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
