name: Appium V2 Tests - iOS

on:
  push:
    branches:
      - 3.x

env:
  CI: true
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  appium:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]
        test-suite: ['other', 'quick']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i --force
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - run: "npm run test:ios:appium-${{ matrix.test-suite }}"
        env: # Or as an environment variable
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}

