name: build
on:
  push:
    branches:
      - 3.x
  pull_request:
    branches:
      - 3.x
    types: 
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    - run: ls -la node_modules/tsd-jsdoc
    - run: npm run def
    - run: npm run dtslint
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - run: npm version prerelease --preid=rc --force