name: Expect Helper Tests

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches:
      - '**'

env:
  CI: true
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  expect-helper-test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/checkout@v4
    - name: Checkout and install dependencies steps
      uses: ./.github/actions/checkoutAndInstallLibs.steps.yml

    - name: run unit tests
      run: ./node_modules/.bin/mocha test/helper/Expect_test.js --timeout 5000
