name: Publish release version to NPM

on:
  push:
    branches:
      - "3.x"

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set npm registry and _authToken
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Unit tests
        run: npm run test:unit

      - name: Generate typings
        run: npm run def

      - name: Lint
        run: npm run lint

      - name: Set version
        run: npm version patch

      - name: Publish package on NPM 📦
        run: npm publish

      - name: Push changes to repository
        run: git push origin && git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
