name: Run Unit tests

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - name: Start mock server
        run: nohup npm run mock-server:start &
      - name: Wait for mock server
        run: |
          for i in {1..20}; do
            curl -sSf http://localhost:3001/api/users && break
            sleep 1
          done
      - run: npm run test:unit
        env:
          GH_PAT: ${{ github.token }}

  runner-tests:
    name: Runner tests
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - name: Start mock server
        run: nohup npm run mock-server:start &
      - name: Wait for mock server
        run: |
          for i in {1..20}; do
            curl -sSf http://localhost:3001/api/users && break
            sleep 1
          done
      - run: npm run test:runner
        env:
          GH_PAT: ${{ github.token }}
