name: WebDriver Tests

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches:
      - '**'

env:
  CI: true
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - run: docker run  --net=host -d --shm-size=2g selenium/standalone-chrome:4.27
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: npm install
        run: |
          npm i
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - name: check
        run: './bin/codecept.js check -c test/acceptance/codecept.WebDriver.js'
        timeout-minutes: 2
        env:
          GH_PAT: ${{ github.token }}
          SELENIUM_HOST: localhost
          SELENIUM_PORT: 4444
      - name: start a server
        run: |
          php -S 0.0.0.0:8000 -t test/data/app &
          sleep 5
      - name: run unit tests
        run: ./node_modules/.bin/mocha test/helper/WebDriver_test.js --exit --reporter @testomatio/reporter/mocha
        timeout-minutes: 10
        env:
          SELENIUM_HOST: localhost
          SELENIUM_PORT: 4444
      - name: run tests
        run: 'timeout 600 bash -c "./bin/codecept.js run -c test/acceptance/codecept.WebDriver.js --grep @WebDriver --debug"'
        timeout-minutes: 12
        env:
          SELENIUM_HOST: localhost
          SELENIUM_PORT: 4444
      - name: cleanup
        run: |
          # Stop PHP server
          pkill -f "php -S 0.0.0.0:8000"
          # Stop Selenium container
          docker stop $(docker ps -q --filter ancestor=selenium/standalone-chrome:4.27) || true
